In [ ]:
#importing necessary libraries
#reading a CSV file using pandas

import pandas as pd

df = pd.read_csv('/content/cstads_2122_pumf.csv')
display(df.head())

,SEQID,PROVID,GRADE,DVGENDER,DVURBAN,DVRES,DVORIENT,DVDESCRIBE,WTPUMF,GH_010,...,BUL_100,BUL_110,BUL_120,DVTY1ST,DVTY2ST,DVLAST30,DVAMTSMK,DVCIGWK,DVNDSMK,DVAVCIGD
0,18338,11,9,2,1,3,2,1,1.164716,2,...,2,2,4,3,7,2,96,996,96,96
1,16111,24,10,1,1,1,2,4,36.141169,3,...,2,2,1,3,7,2,96,996,96,96
2,20587,10,7,2,1,1,2,1,1.448578,2,...,2,2,1,3,7,2,96,996,96,96
3,54568,12,8,99,2,1,1,1,3.036660,4,...,2,2,2,3,7,2,96,996,96,96
4,40991,10,7,1,2,1,2,1,3.745233,2,...,99,99,99,3,7,2,96,996,96,96

Data Cleaning and Impute Missing Value

In [ ]:
#Calculate the number of missing values in each column

missing_values = df.isnull().sum()
print("Missing Values in Each Column:")
missing_values

Missing Values in Each Column:

SEQID           2
PROVID          0
GRADE           0
DVGENDER     5025
DVURBAN         0
DVRES        1303
GH_010       2498
GH_020       3395
SS_010         85
SS_020      51574
TS_011        262
SS_030         84
SS_040        103
SC_010        970
ALC_010       571
ALC_020      3626
ALC_030     33514
ALC_040      3551
ALC_050      2556
ALC_060     46966
ALC_071      2205
CAN_010       523
CAN_020       301
CAN_030     48601
CAN_040       362
CAN_130      1212
PH_010       5737
PH_020       5828
PH_110       7045
PH_120       7057
PH_070       8734
PH_080       9228
CA_020      12054
ALC_080     12085
CAN_050     15947
BEH_010      2140
BEH_020      2327
BUL_010      2112
BUL_020      1943
BUL_030      2089
BUL_040      2120
DVTY1ST       177
DVTY2ST       532
DVLAST30      375
DVAMTSMK     1135
dtype: int64

In [ ]:
#Impute Mean for Missing Value

# Calculate and Impute the mean of SS_020 where the value is not equal to 2
mean_ss_020 = df.loc[df['SS_020'] != 2, 'SS_020'].mean()
df.loc[df['SS_020'] == 2, 'SS_020'] = mean_ss_020

# Calculate and Impute the mean of ALC_030 where the value is not equal to 3
mean_alc_030 = df.loc[df['ALC_030'] != 3, 'ALC_030'].mean()
df.loc[df['ALC_030'] == 3, 'ALC_030'] = mean_alc_030

# Calculate and Impute the mean of ALC_060 where the value is not equal to 2
mean_alc_060 = df.loc[df['ALC_060'] != 2, 'ALC_060'].mean()
df.loc[df['ALC_060'] == 2, 'ALC_060'] = mean_alc_060

#Impute means for these columns
columns_to_impute = ['PH_010', 'PH_020', 'PH_110', 'PH_120', 'PH_070', 'PH_080', 'CA_020', 'ALC_080', 'CAN_050']
for column in columns_to_impute:
  mean_value = df.loc[df[column] != 5, column].mean()
  df[column] = df[column].fillna(mean_value).replace(5, mean_value)

df.head()

,SEQID,PROVID,GRADE,DVGENDER,DVURBAN,DVRES,GH_010,GH_020,SS_010,SS_020,...,BEH_010,BEH_020,BUL_010,BUL_020,BUL_030,BUL_040,DVTY1ST,DVTY2ST,DVLAST30,DVAMTSMK
0,18338.0,11,9,2.0,1,3.0,2.0,3.0,2.0,NaN,...,1.0,1.0,2.0,1.0,2.0,2.0,3.0,7.0,2.0,0.0
1,16111.0,24,10,1.0,1,1.0,3.0,3.0,2.0,NaN,...,3.0,4.0,2.0,2.0,2.0,2.0,3.0,7.0,2.0,0.0
2,20587.0,10,7,2.0,1,1.0,2.0,1.0,2.0,NaN,...,4.0,4.0,2.0,2.0,2.0,2.0,3.0,7.0,2.0,0.0
3,54568.0,12,8,NaN,2,1.0,4.0,5.0,2.0,NaN,...,4.0,4.0,1.0,2.0,2.0,2.0,3.0,7.0,2.0,0.0
4,401.0,10,7,1.0,2,1.0,2.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,7.0,2.0,0.0

In [ ]:
# prompt: Impute mode for missing values of the following columns: DVGENDER, DVURBAN, DVRES, SS_010, SS_030, SS_040, ALC_010, CAN_010, BUL_010, BUL_020, BUL_030, BUL_040, DVLAST30
# columns_to_impute median = ['DVTY1ST', 'DVTY2ST', 'DVAMTSMK', 'BEH_010', 'BEH_020', 'CAN_130', 'CAN_040', 'CAN_030', 'CAN_020', 'ALC_071', 'ALC_060', 'ALC_050', 'ALC_040', 'ALC_030', 'ALC_020', 'SC_010', 'TS_011', 'SS_020', 'GH_010', 'GH_020']

columns_mode = ['DVGENDER', 'DVURBAN', 'DVRES', 'SS_010', 'SS_030', 'SS_040', 'ALC_010', 'CAN_010', 'BUL_010', 'BUL_020', 'BUL_030', 'BUL_040', 'DVLAST30']
columns_median = ['DVTY1ST', 'DVTY2ST', 'DVAMTSMK', 'BEH_010', 'BEH_020', 'PH_010', 'PH_020', 'PH_070', 'PH_080', 'PH_110', 'PH_120', 'CAN_130', 'CA_020', 'CAN_050', 'ALC_080', 'CAN_040', 'CAN_030', 'CAN_020', 'ALC_071', 'ALC_060', 'ALC_050', 'ALC_040', 'ALC_030', 'ALC_020', 'SC_010', 'TS_011', 'SS_020', 'GH_010', 'GH_020']

for column in columns_mode:
    mode_value = df[column].mode()[0]  # Get the first mode in case of multiple modes
    df[column] = df[column].fillna(mode_value)

for column in columns_median:
    median_value = df[column].median()
    df[column] = df[column].fillna(median_value)

In [ ]:
# Calculate the number of missing values in each column
missing_values = df.isnull().sum()

# Display the results
print("Missing Values in Each Column:")
missing_values

Missing Values in Each Column:

SEQID       2
PROVID      0
GRADE       0
DVGENDER    0
DVURBAN     0
DVRES       0
GH_010      0
GH_020      0
SS_010      0
SS_020      0
TS_011      0
SS_030      0
SS_040      0
SC_010      0
ALC_010     0
ALC_020     0
ALC_030     0
ALC_040     0
ALC_050     0
ALC_060     0
ALC_071     0
CAN_010     0
CAN_020     0
CAN_030     0
CAN_040     0
CAN_130     0
PH_010      0
PH_020      0
PH_110      0
PH_120      0
PH_070      0
PH_080      0
CA_020      0
ALC_080     0
CAN_050     0
BEH_010     0
BEH_020     0
BUL_010     0
BUL_020     0
BUL_030     0
BUL_040     0
DVTY1ST     0
DVTY2ST     0
DVLAST30    0
DVAMTSMK    0
dtype: int64

In [ ]:
from google.colab import files

df.to_csv('capston_filled.csv')
files.download('capston_filled.csv')